# Generated by Django 5.2 on 2025-04-19 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_cuidador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_veterinario', to=settings.AUTH_USER_MODEL),
        ),
    ]
