# Generated by Django 5.2 on 2025-04-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mascota_cuidador_alter_historiamedica_veterinario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('paseo', 'Paseo'), ('alimentacion', 'Alimentación'), ('juego', 'Juego'), ('baño', 'Baño'), ('vacuna', 'Vacuna'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion_min', models.PositiveIntegerField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.mascota')),
            ],
        ),
    ]
