# Generated by Django 5.2 on 2025-04-21 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eventomascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorridoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_metros', models.PositiveIntegerField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='api.mascota')),
            ],
        ),
    ]
