# Generated by Django 5.2 on 2025-05-26 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=150)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuidador', models.ForeignKey(limit_choices_to={'tipo': 'cuidador'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_realizados', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_servicios', to='api.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='PaseoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('latitudes', models.JSONField()),
                ('longitudes', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paseos_programados', to='api.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='ControlFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.CharField(max_length=15)),
                ('talla', models.CharField(max_length=15)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_fisicos', to='api.mascota')),
            ],
            options={
                'unique_together': {('mascota', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='HorarioNoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('veterinario', models.ForeignKey(limit_choices_to={'tipo': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_no_disponibles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('veterinario', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
